apiVersion: v1
kind: Namespace
metadata:
  name: trading-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-streamer
  namespace: trading-system
  labels:
    app: market-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-streamer
  template:
    metadata:
      labels:
        app: market-streamer
    spec:
      containers:
      - name: market-streamer
        image: market-streamer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          protocol: UDP
          name: udp-stream
        env:
        - name: BIND_ADDR
          value: "0.0.0.0:8888"
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        # No probes - let's see if the app starts first
---
apiVersion: v1
kind: Service
metadata:
  name: market-streamer-service
  namespace: trading-system
spec:
  selector:
    app: market-streamer
  ports:
  - port: 8888
    targetPort: 8888
    protocol: UDP
    name: udp-stream
  type: ClusterIP